# Description: Resize Images in specified folder
#
# required values:
#   var.IMAGE_DIR_IN      : directory containing source images
#   var.IMAGE_DIR_OUT     : destination directory for resized images
#   var.NEW_RESOLUTION    : desired resolution for resized images

name: resize-images

on:
  workflow_dispatch:

env:
  IMAGE_DIR_IN: ${{ vars.IMAGE_DIR_IN || 'images/src'}}
  IMAGE_DIR_OUT: ${{ vars.IMAGE_DIR_OUT || 'images'}}
  NEW_RESOLUTION: ${{ vars.NEW_RESOLUTION || '600x'}}

jobs:
  resize-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Image Resizer Action
      uses: sharadcodes/img-resizer@v1.1
      with:
        image-folder: ${{ env.IMAGE_DIR_IN }}
        new-resolution: ${{ env.NEW_RESOLUTION }}
        output-folder: ${{ env.IMAGE_DIR_OUT }}
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'images/'
        author_name: "github-actions[bot]"
        author_email: "github-actions@users.noreply.github.com"
        message: |
          Images Resized by Github action\n
          ```
          ${{steps.resize-images.outputs.images_changed}}
          ```
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
